version: '3.7'

services:
  config-server:
    image: indiagator/config-server:0.1
    ports:
      - "8071:8071"
    networks:
      backend:
        aliases:
          - "config-server"
  eureka-server:
    image: indiagator/eureka-server-image:0.4
    environment:
      PROFILE: "default"
      CONFIGSERVER_URI: "http://config-server:8071"
      CONFIGSERVER_PORT: "8071"
    depends_on:
      config-server:
        condition: service_started
    ports:
      - "8070:8070"
    networks:
      backend:
        aliases:
          - "eureka-server"

  gateway-server:
    image: indiagator/gateway-server:0.1
    environment:
      PROFILE: "default"
      CONFIGSERVER_URI: "http://config-server:8071"
      CONFIGSERVER_PORT: "8071"
      DATABASESERVER_PORT: "5432"
    depends_on:
      config-server:
        condition: service_started
      eureka-server:
        condition: service_started
    ports:
      - "8072:8072"
    networks:
      - backend

networks:
  backend:
    driver: bridge